vim.opt.nu = true -- Display Line Numbers
vim.opt.relativenumber = true -- Display Relative Line Numbers (set to false if you want to improve your mental calculation skills)
vim.opt.tabstop = 4 -- Make tab char appears 4 cells wide
vim.opt.softtabstop = 4 -- Move cursor 4 cells for each tab
vim.opt.shiftwidth = 4 -- Use 4 spaces on auto-indent
vim.opt.expandtab = true -- Insert spaces instead of tabs
vim.opt.smartindent = true -- Automatically indent on new lines
vim.opt.wrap = false -- Line wrapping
vim.opt.termguicolors = true -- Enable 24-bit RGB color. Uses GUI attriutes for highlight instead of cterm
vim.opt.scrolloff = 8 -- Display Lines underneath / above cursor when scrolling
vim.opt.cmdheight = 0 -- Height of the cmd line. Setting to 0 will replace the statusline when entering a command
vim.o.exrc = true
